language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#  - "nightly"
#virtualenv:
#    system_site_packages: NO !!! 
# the system python and the one from travis have been compiled with different options 
addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libhdf5-serial-1.8.4
      - libhdf5-serial-dev
      - gfortran
      - libatlas-base-dev
      - libqtcore4
#For GPU:
      - dkms 
      - fglrx-amdcccle 
      - fglrx 
      - opencl-headers   
      - libboost1.48-dev
      - libboost-python-dev
      - libboost-python1.48
# command to install dependencies
install:
  - travis_wait pip install cython --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse
  - "pip install --trusted-host www.edna-site.org -r requirements_travis.txt"
  - "python info_platform.py"
  - "python setup.py build install"
# command to run tests
script: 
  - "python setup.py build test"
  - "(WD=$(pwd); cd /tmp && python $WD/run_tests.py -v)"
