os:
  - linux
#  - osx

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
   - python: 3.7
     dist: xenial

#virtualenv:
#    system_site_packages: NO !!!
# the system python and the one from travis have been compiled with different options

addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libhdf5-dev
      - gfortran
      - libatlas-base-dev
      - libqtcore4
#For OpenCL:
      - python-cffi
      - python3-cffi
      - ocl-icd-libopencl1
      - opencl-headers
      - python-pyopencl
      - python3-pyopencl
# command to install dependencies

before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/before_install-linux.sh; fi"
#  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"

install:
  - "python ci/info_platform.py"
  - "pip install --upgrade pip"
  - "pip install cython"
  - "pip install --upgrade numpy --no-binary :all:"
  - "pip install --upgrade h5py mako"  
  - "pip install --upgrade -r ci/requirements_travis.txt"
  - "python ci/info_platform.py"
  - "python setup.py build"
  - "python setup.py bdist_wheel"
  - "pip install --pre --no-index --find-links dist/ pyFAI"

# command to run tests
script:
  - "python ./run_tests.py -m"
  - "python ./run_tests.py -m --installed"

