language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#  - "nightly"
# command to install dependencies
install:
  - "pip install -r requirements_travis.txt"
  - "python setup.py build install"
# command to run tests
script: 
  - "python setup.py build test"
  - "(cd /tmp && python -c 'import pyFAI, sys; print(sys.version); print(pyFAI.version); pyFAI.tests()')"
