language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
#  - "nightly"
addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy
      - python3-scipy
# command to install dependencies
install:
  - "pip install -r requirements_travis.txt"
  - "python setup.py build install"
# command to run tests
script: 
  - "python setup.py build test"
  - "(WD=$(pwd); cd /tmp && python $WD/run_tests)"
