# AppVeyor.com is a Continuous Integration service to build and run tests Windows
# https://ci.appveyor.com/project/kif/pyFAI

os:
    - Visual Studio 2015

cache:
    - '%LOCALAPPDATA%\pip\Cache'

# fetch repository as zip archive
shallow_clone: true

environment:
    global:
        WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"
        VENV_BUILD_DIR: "venv_build"
        VENV_TEST_DIR: "venv_test"

    matrix:
        # Python 2.7
        - PYTHON_DIR: "C:\\Python27-x64"
          PYTHON_VERSION: "2.7.11"
          PYTHON_ARCH: "64"

        # Python 3.4
        - PYTHON_DIR: "C:\\Python27-x64"
          PYTHON_VERSION: "3.4.3"
          PYTHON_ARCH: "64"

        # Python 3.5
        - PYTHON_DIR: "C:\\Python35-x64"
          PYTHON_VERSION: "3.5.0"
          PYTHON_ARCH: "64"

install:
    # Add Python to PATH
    - "SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"

    # Upgrade distribution modules
    # Disabled as pip uprade fails
    # - "pip install --upgrade setuptools"
    # - "pip install --upgrade pip"

    # Install virtualenv
    - "pip install virtualenv"
    - "virtualenv --version"

build_script:
    # Create build virtualenv
    - "virtualenv --clear %VENV_BUILD_DIR%"
    - "%VENV_BUILD_DIR%\\Scripts\\activate.bat"

    # Install buils dependencies
    - "pip install wheel"
    - "pip install --trusted-host www.silx.org --find-links http://www.silx.org/pub/wheelhouse/ numpy cython"
    - "pip install --trusted-host www.silx.org --find-links http://www.silx.org/pub/wheelhouse/ pyparsing scipy"
    - "pip install --trusted-host www.silx.org --find-links http://www.silx.org/pub/wheelhouse/ -r ci/requirements_appveyor.txt"

    # Print Python info
    - "python ci\\info_platform.py"
    - "pip freeze"

    # Build
    - "del pyFAI\\ext\\histogram.c"
    # OpenMP is not available on python 3.4
    - python setup.py build --no-openmp" 
    - python setup.py test" 
    - "python setup.py bdist_wheel bdist_msi"
    - ps: "ls dist"
    # Install the generated wheel package to test it
    - "pip install --pre --no-index --find-links dist/ pyFAI"

  # Leave build virtualenv
    - "%VENV_BUILD_DIR%\\Scripts\\deactivate.bat"
    - "rmdir %VENV_BUILD_DIR% /s /q"


# Not a .NET project, we build pyFAI in the install step instead
build: false

test_script:
    # Create test virtualenv
    - "virtualenv --clear %VENV_TEST_DIR%"
    - "%VENV_TEST_DIR%\\Scripts\\activate.bat"

    # Install the generated wheel package to test it
    - "pip install --pre --find-links dist/ --trusted-host www.silx.org --find-links http://www.silx.org/pub/wheelhouse/ pyFAI"

    # Print Python info
    - "python ci\\info_platform.py"
    - "pip freeze"

    - "python run_tests.py"

    # Leave test virtualenv
    - "%VENV_TEST_DIR%\\Scripts\\deactivate.bat"
    - "rmdir %VENV_TEST_DIR% /s /q"

artifacts:
    # Archive the generated wheel package in the ci.appveyor.com build report.
    - path: dist\*
